#!/usr/bin/env python
"""Simple upload script to push up into the testing directory a local build
"""

from __future__ import print_function

from toollib import *

# Get main ipython dir, this will raise if it doesn't pass some checks
ipdir = get_ipdir()
distdir = pjoin(ipdir, 'dist')

# Load release info
execfile(pjoin(ipdir, 'IPython','core','release.py'))

# Build site addresses for file uploads
testing_site = f'{archive}/testing/{version}'

cd(distdir)

# Create remote path if it doesn't exist.
sh(f'ssh {archive_user} "mkdir -p {archive_dir}/testing/{version}" ')
sh(f'scp * {testing_site}')
